Setup.py
cafltar/plfa_tools_aggregator pull request #7
Opened 2020-01-21 18:24 UTC by patrickmorrell17

2020-01-22 17:14 UTC, bryanrcarlson requested changes
Looking good! Some details need updated, then I think it's ready for merge

2020-01-22 17:14 UTC, bryanrcarlson commented on setup.py
> +  name = 'PLFA_Tools_Aggregator',         # How you named your package folder (MyLib)
`name = 'plfatools'`

Users can use: `pip install plfatools`

2020-01-22 17:14 UTC, bryanrcarlson commented on setup.py
> +  packages = ['PLFA_Tools_Aggregator'],   # Chose the same as "name"
I think this is `packages = ['pflatools']` as well

2020-01-22 17:14 UTC, bryanrcarlson commented on setup.py
> +  version = '0.0.1',      # Start with a small number and increase it with every change you make
Lets start at `version = '0.1.0'`. I think 0.0.1 suggests alpha (internal only). I think we're more like beta (external use, but with extreme caution).

2020-01-22 17:14 UTC, bryanrcarlson commented on setup.py
> +  author = 'Patrick Morrell',                   # Type in your name
`author = 'Patrick Morrell, Bryan Carlson'`

2020-01-22 17:14 UTC, bryanrcarlson commented on setup.py
> +  download_url = 'https://github.com/cafltar/plfa_tools_aggregator.git',    # I explain this later on
We'll need to update this later to the release commit, once we finalize and tag it

2020-01-22 17:14 UTC, bryanrcarlson commented on setup.py
> +    'Development Status :: 3 - Alpha',      # Chose either "3 - Alpha", "4 - Beta" or "5 - Production/Stable" as the current state of your package
I think 4 - Beta?

2020-01-22 20:14 UTC, patrickmorrell17 commented
Ok- I will make these changes and re-push the branch! Do you think I need to delete the comments on the setup.py?

2020-01-24 16:44 UTC, bryanrcarlson commented
@patrickmorrell17 , yeah, feel free to remove the comments in setup.py. Thanks!

2020-01-27 23:15 UTC, bryanrcarlson approved these changes

2020-01-28 00:12 UTC, merged